---
- name: Create DBA
  community.mysql.mysql_user:
    login_user: root
    name: "dba"
    # SELECT PASSWORD('enter-password-here');
    password: "*0C23F19DB8283F44BBDD6C3DD88EAA0A7F3A3451"
    encrypted: true
    host: "%"
    priv: "*.*:ALL,GRANT"
    state: present
  tags:
    - create-dba

